<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE patterngroup [
  <!-- Pattern Group Element -->
  <!ELEMENT patterngroup (pattern)+>
  <!ATTLIST patterngroup version CDATA #REQUIRED>
  <!ATTLIST patterngroup label CDATA "">

  <!-- Pattern Element -->
  <!ELEMENT pattern (word)+>
  <!ATTLIST pattern name ID #REQUIRED>
  <!ATTLIST pattern description CDATA "">
  <!ATTLIST pattern class CDATA #REQUIRED>
  <!ATTLIST pattern weight CDATA "1">
  <!ATTLIST pattern preprocess CDATA "false">
  <!ATTLIST pattern label CDATA "">

  <!-- Word element -->
  <!ELEMENT word EMPTY>
  <!ATTLIST word min CDATA "1">
  <!ATTLIST word max CDATA "1">
  <!ATTLIST word contextual CDATA "false">
  <!ATTLIST word label CDATA "">
  <!-- Specific Word Matching -->
  <!ATTLIST word lemma CDATA "*">
  <!ATTLIST word word CDATA "*">
  <!-- Parts of Speech -->
  <!ATTLIST word pos CDATA "*">
  <!ATTLIST word expos CDATA "">
  <!-- Dependencies -->
  <!ATTLIST word deps CDATA "*">
  <!ATTLIST word exdeps CDATA "">
  <!ATTLIST word depnum CDATA "1">
  <!-- Additional Type -->
  <!ATTLIST word type CDATA "*">
  <!ATTLIST word extype CDATA "">
  <!ATTLIST word typenum CDATA "1">
  <!ATTLIST word ner CDATA "*">

]>

<patterngroup label="spatial-patterns-improved" version="1.0">
  <!-- PREPROCESSING PATTERNS -->
  <pattern name="noun-geonoun compound" class="GNN" description="" weight="1" preprocess="true"> 
    <word pos="DT" min="0" max="1"/>
    <word pos="NN*,JJ*" extype="GNN" min="0" max="2"/>
    <word pos="NN*" type="GNN" max="3"/>
  </pattern>
  <pattern name="geonoun-noun compound" class="GNN" description="" weight="1" preprocess="true"> 
    <word pos="DT" min="0" max="1"/>
    <word pos="NN*" type="GNN" max="3"/>
    <word pos="NN*" extype="GNN" max="3"/>
  </pattern>
  <pattern name="geonoun-of-noun compound" class="GNN" description="" weight="1" preprocess="true"> 
    <word pos="DT" min="0" max="1"/>
    <word pos="NN*" type="GNN" max="2"/>
    <word word="of"/>
    <word pos="NN*" max="3"/>
  </pattern>
  <pattern name="strict-geonoun compound" class="GNN" description="" weight="1" preprocess="true"> 
    <word pos="DT" min="0" max="1"/>
    <word pos="NN*" type="GNN" max="3"/>
  </pattern>
  <!-- GENERIC NOUNS -->
  <pattern name="nonspatial-noun compound" class="NOUN" description="" weight="1" preprocess="true"> 
    <word pos="DT" min="0" max="1"/>
    <word pos="NN*,JJ*" extype="GNN,LCS" ner="O" min="0" max="3"/>
    <word pos="NN*" extype="GNN,LCS,QTF" ner="O" max="3"/>
  </pattern>
  <pattern name="possessed-geonoun" class="GNN" description="" weight="1" preprocess="true"> 
    <word pos="POS" max="1"/>
    <word pos="NN*" type="GNN" extype="QTF" max="3"/>
  </pattern>
  <pattern name="possessed-location-specifier" class="LCS" description="" weight="1" preprocess="true"> 
    <word pos="POS" max="1"/>
    <word type="LCS" max="2"/>
  </pattern>
  <!-- LOCATION SPECIFIER -->
  <pattern name="location-specifier" class="LCS" description="" weight="1" preprocess="true"> 
    <word pos="DT" min="0" max="1"/>
    <word pos="NN*" type="LCS" max="2" />
  </pattern>
  <!-- SPATIALLY SIGNIFICANT VERB -->
  <pattern name="single-spatial-verb" class="SVB" description="" weight="1" preprocess="true"> 
    <word type="SSV" max="2" />
  </pattern>
  <pattern name="spatial-verb" class="SVB" description="" weight="1" preprocess="true"> 
    <word pos="MD" min="0" max="1"/>
    <word pos="RB" min="0" max="1"/>
    <word type="SSV" max="2" />
  </pattern>
  <pattern name="complex-spatial-verb" class="SVB" description="" weight="1" preprocess="true"> 
    <word pos="MD" min="0" max="1"/>
    <word pos="VB*" min="1" max="1"/>
    <word pos="RB" min="0" max="1"/>
    <word type="SSV" max="2" />
  </pattern>
  <!-- NER -->
  <pattern name="entity-person" class="PERSON" description="" weight="1" preprocess="true"> 
    <word pos="DT" min="0" max="1"/>
    <word pos="NN*,JJ*,IN*" ner="PERSON" max="5" />
  </pattern>
  <pattern name="entity-location" class="LOCATION" description="" weight="1" preprocess="true"> 
    <word pos="DT" min="0" max="1"/>
    <word pos="NN*,JJ*,IN*" ner="LOCATION,CITY,COUNTRY,STATE_OR_PROVINCE" max="4" />
  </pattern>
  <!-- <pattern name="entity-location-described" class="LOCATION" description="" weight="1" preprocess="true"> 
    <word pos="NN*,JJ*,IN*" ner="LOCATION,CITY,COUNTRY,STATE_OR_PROVINCE" max="4" />
    <word pos="," />
    <word pos="NN*,JJ*,IN*" ner="LOCATION,CITY,COUNTRY,STATE_OR_PROVINCE" max="4" />
  </pattern> -->
  <pattern name="entity-org" class="ORG" description="" weight="1" preprocess="true"> 
    <word pos="DT" min="0" max="1"/>
    <word pos="NN*,JJ*,IN*" ner="ORGANIZATION" max="5" />
  </pattern>
  <pattern name="entity-misc" class="MISC" description="" weight="1" preprocess="true"> 
    <word pos="DT" min="0" max="1"/>
    <word pos="NN*,JJ*,IN*" ner="MISC" max="5" />
  </pattern>
  <!-- DIRECTIONS -->
  <pattern name="direction compound" class="DIR" description="" weight="1" preprocess="true"> 
    <word pos="DT" min="0" max="1"/>
    <word pos="NN*,JJ*" type="DIR" max="3" />
  </pattern>
  <!-- QUANTIFIERS -->
  <pattern name="quantifier" class="QTF" description="" weight="1" preprocess="true"> 
    <word pos="NN*,CD*,JJ*" type="QTF" max="3" />
  </pattern>
  <pattern name="entity-quantifier" class="QTF" description="" weight="1" preprocess="true"> 
    <word ner="NUMBER" max="3" />
  </pattern>

  <!-- POST-PROCESSING PATTERNS -->
  <!-- SPATIAL RELATION PATTERNS -->
  <!-- <pattern name="sverb qual rel geoentity" class="spatial-rel" description="" weight="2"> 
    <word word="SVB" />
    <word type="SRQ" min="0" max="2"/>
    <word type="SVS" max="2"/>
    <word word="GNN,LOCATION,ORG,MISC" max="2" />
  </pattern> -->
  <pattern name="sverb qual rel geoentity" class="spatial-rel" description="" weight="2"> 
    <word word="SVB" />
    <word type="SRQ" min="0" max="2"/>
    <word type="SVS" max="2"/>
    <word word="GNN,LOCATION" max="2" />
  </pattern>
  <pattern name="sverb qual rel spatial" class="spatial-rel" description="" weight="2"> 
    <word word="SVB" />
    <word type="SRQ" min="0" max="2"/>
    <word type="SVS" max="2"/>
    <word word="NOUN" max="2" />
  </pattern>
  <pattern name="rel ssv spatial" class="spatial-rel" description="" weight="2"> 
    <word type="SVS" max="2"/>
    <word word="SVB" />
    <word word="NOUN" max="2" />
  </pattern>
  <pattern name="rel lcs rel geoentity" class="spatial-rel" description="" weight="2"> 
    <word type="SVS" max="2"/>
    <word word="LCS" max="2" />
    <word type="SVS" max="2"/>
    <word word="GNN,LOCATION" max="2" />
  </pattern>
  <pattern name="rel lcs rel spatial" class="spatial-rel" description="" weight="2"> 
    <word type="SVS" max="2"/>
    <word word="LCS" max="2" />
    <word type="SVS" max="2"/>
    <word word="NOUN" max="2" />
  </pattern>
  <pattern name="noun svb rel noun" class="spatial-verb" description="" weight="2"> 
    <word word="NOUN" max="2" />
    <word word="SVB" max="2" />
    <word type="SVS" max="2"/>
    <word word="NOUN" max="2" />
  </pattern>
  <pattern name="gnn svb rel gnn" class="spatial-verb" description="" weight="2"> 
    <word word="GNN,LOCATION" max="2" />
    <word word="SVB" max="2" />
    <word type="SVS" max="2"/>
    <word word="GNN,LOCATION" max="2" />
  </pattern>
  <pattern name="noun svb rel gnn" class="spatial-verb" description="" weight="2"> 
    <word word="NOUN" max="2" />
    <word word="SVB" max="2" />
    <word type="SVS" max="2"/>
    <word word="GNN,LOCATION" max="2" />
  </pattern>
  <pattern name="svb noun rel gnn" class="spatial-verb" description="" weight="2"> 
    <word word="SVB" max="2" />
    <word word="NOUN" max="2" />
    <word type="SVS" max="2"/>
    <word word="DIR" min="0" max="1" />
    <word word="GNN,LOCATION" max="2" />
  </pattern>
  <pattern name="verb dir rel" class="spatial-verb" description="" weight="2"> 
    <word word="SVB" max="2" />
    <word word="DIR" min="0" max="1" />
    <word type="SVS" max="2" />
  </pattern>
  <pattern name="verb rel dir" class="spatial-verb" description="" weight="2"> 
    <word word="SVB" max="2" />
    <word type="SVS" max="2" />
    <word word="DIR" max="1" />
  </pattern>
  <pattern name="gnn rel lcs rel gnn" class="spatial-verb" description="" weight="2"> 
    <word word="GNN,LOCATION" max="2" />
    <word type="SVS" max="2" />
    <word word="LCS" max="2" />
    <word type="SVS" max="2" />
    <word word="GNN,LOCATION" max="2" />
  </pattern>
  <pattern name="gnn rel gnn" class="spatial-verb" description="" weight="2"> 
    <word word="GNN,LOCATION" max="2" />
    <word type="SVS" max="2" />
    <word word="DIR" min="0" max="1" />
    <word word="GNN,LOCATION" max="2" />
  </pattern>
  <pattern name="noun rel gnn" class="spatial-verb" description="" weight="2"> 
    <word word="NOUN,PERSON" max="2" />
    <word type="SVS" max="2" />
    <word word="DIR" min="0" max="1" />
    <word word="GNN,LOCATION" max="2" />
  </pattern>
  <pattern name="rel gnn ssv gnn" class="spatial-verb" description="" weight="2"> 
    <word type="SVS" max="2" />
    <word word="DIR" min="0" max="1" />
    <word word="GNN,LOCATION" max="2" />
    <word word="SSV" max="2" />
    <word word="GNN,LOCATION" max="2" />
  </pattern>
  <!--
  <pattern name="rel-dir-lcs-rel-gnn" class="spatial-rel" description="" weight="3"> 
    <word type="SVS" max="2"/>
    <word word="DIR" max="1" />
    <word word="LCS" max="2" />
    <word type="SVS" max="2"/>
    <word word="GNN,LOCATION,ORG,MISC" max="2" />
  </pattern>
  <pattern name="rel-gnn" class="spatial-rel" description="" weight="1"> 
    <word type="SVS" max="2"/>
    <word word="GNN,LOCATION,ORG,MISC" max="2" />
  </pattern>
  <pattern name="rel-non-gnn" class="spatial-rel" description="" weight="1"> 
    <word type="SVS" max="2"/>
    <word word="NOUN" max="2" />
  </pattern>
  <pattern name="qtf-gnn-rel" class="spatial-rel" description="" weight="1"> 
    <word word="QTF" max="2"/>
    <word word="GNN,NN" max="2" />
    <word type="SVS" max="2" />
  </pattern>
  <pattern name="rel-gnn-pos" class="spatial-rel" description="" weight="1"> 
    <word type="SVS" max="2"/>
    <word word="GNN,LOCATION,ORG,MISC" max="2" />
    <word pos="POS" />
    <word word="GNN,LCS" max="3" />
  </pattern>
  <pattern name="qual-dir-rel" class="spatial-rel" description="" weight="1"> 
    <word type="SRQ" min="1" max="2"/>
    <word word="DIR" min="1" max="2"/>
    <word type="SVS" max="2"/>
  </pattern>

  <pattern name="rel-dir-rel" class="spatial-rel" description="" weight="1"> 
    <word word="SVB" max="2"/>
    <word word="DIR" max="2"/>
    <word type="SVS" max="2"/>
  </pattern>

  <pattern name="spatial-verb-rel-basic" class="spatial-verb" description="" weight="2"> 
    <word pos="VB*" min="0" max="1"/>
    <word word="SVB" max="2"/>
    <word type="SVS" max="2"/>
  </pattern>

  <pattern name="spatial-verb-noun-rel-gnn" class="spatial-verb" description="" weight="2"> 
    <word word="SVB" max="2"/>
    <word word="NOUN,GNN,PERSON" />
    <word type="SVS" max="2"/>
    <word type="GNN,LOCATION" max="2"/>
  </pattern>

  <pattern name="spatial-verb-noun-rel-noun" class="spatial-verb" description="" weight="2"> 
    <word word="SVB" max="2"/>
    <word word="NOUN,GNN,PERSON" />
    <word type="SVS" max="2"/>
    <word type="NOUN" max="2"/>
  </pattern>

  <pattern name="geospatial-verb-rel-actor" class="spatial-verb" description="" weight="3"> 
    <word pos="NN*,PRP*" min="1" max="2"/>
    <word pos="VB*" min="0" max="1"/>
    <word word="SVB" max="2"/>
    <word type="SVS" max="2"/>
    <word word="DIR" min="0" max="2" />
    <word word="GNN,LOCATION,ORG,MISC" max="2" />
  </pattern>
  <pattern name="geospatial-verb-rel-person" class="spatial-verb" description="" weight="3"> 
    <word word="PERSON" min="1" max="2"/>
    <word pos="VB*" min="0" max="1"/>
    <word word="SVB" max="2"/>
    <word type="SVS" max="2"/>
    <word word="DIR" min="0" max="2" />
    <word word="GNN,LOCATION,ORG,MISC" max="2" />
  </pattern>
  <pattern name="spatial-verb-rel-actor" class="spatial-verb" description="" weight="3"> 
    <word pos="NN*,PRP*" min="1" max="2"/>
    <word pos="VB*" min="0" max="1"/>
    <word word="SVB" max="2"/>
    <word type="SVS" max="2"/>
    <word word="DIR" min="0" max="2" />
    <word word="NOUN" max="2" />
  </pattern>
  <pattern name="spatial-verb-rel-noun" class="spatial-verb" description="" weight="3"> 
    <word word="NOUN" min="1" max="2"/>
    <word pos="VB*" min="0" max="1"/>
    <word word="SVB" max="2"/>
    <word type="SVS" max="2"/>
    <word word="DIR" min="0" max="2" />
    <word word="NOUN" max="2" />
  </pattern>
  <pattern name="spatial-verb-basic" class="spatial-verb" description="" weight="1"> 
    <word pos="VB*" min="0" max="1"/>
    <word word="SVB" max="2"/>
  </pattern>
  <pattern name="rel-spatial-verb" class="spatial-verb" description="" weight="1"> 
    <word type="SVS" min="1" max="2"/>
    <word word="SVB" max="2"/>
  </pattern>
  <pattern name="spatial-verb-with-noun" class="spatial-verb" description="" weight="1"> 
    <word word="NOUN" min="1" max="2"/>
    <word pos="MD" min="0" max="2"/>
    <word pos="VB*" min="0" max="2"/>
    <word word="SVB" max="2"/>
  </pattern>
  <pattern name="spatial-verb-with-actor" class="spatial-verb" description="" weight="1"> 
    <word pos="NN*,PRP*" min="1" max="2"/>
    <word pos="MD" min="0" max="2"/>
    <word pos="VB*" min="0" max="2"/>
    <word word="SVB" max="2"/>
  </pattern>
  <pattern name="spatial-verb-with-person" class="spatial-verb" description="" weight="1"> 
    <word word="PERSON" min="1" max="2"/>
    <word pos="MD" min="0" max="2"/>
    <word pos="VB*" min="0" max="2"/>
    <word word="SVB" max="2"/>
  </pattern>

  
  <pattern name="geo-spatial-ner-vb-dir" class="non-spatial" description="" weight="1"> 
    <word word="GNN,LOCATION,ORG,MISC,PERSON" min="1" max="2"/>
    <word pos="VB*" extype="SSV" min="0" max="2"/>
    <word pos="MD*" min="0" max="2"/>
    <word pos="VB*" extype="SSV" min="1" max="2"/>
    <word word="DIR" min="1" max="2"/>
  </pattern>
  <pattern name="spatial-ner-vb-dir" class="non-spatial" description="" weight="1"> 
    <word pos="NN*" min="1" max="2"/>
    <word pos="VB*" extype="SSV" min="0" max="2"/>
    <word pos="MD*" min="0" max="2"/>
    <word pos="VB*" extype="SSV" min="1" max="2"/>
    <word word="DIR" min="1" max="2"/>
  </pattern> -->
  <pattern name="lcs" class="object" description="" weight="1"> 
    <word word="LCS" min="1" max="2"/>
  </pattern>
  <pattern name="spatialverb" class="object" description="" weight="1"> 
    <word word="SVB" min="1" max="2"/>
  </pattern>
  <pattern name="noun" class="object" description="" weight="1"> 
    <word word="NOUN" min="1" max="2"/>
  </pattern>
  <pattern name="dir" class="object" description="" weight="1"> 
    <word word="DIR" min="1" max="2"/>
  </pattern>
  <pattern name="qtf" class="object" description="" weight="1"> 
    <word word="QTF" min="1" max="2"/>
  </pattern>
  <pattern name="person" class="object" description="" weight="1"> 
    <word word="PERSON" min="1" max="2"/>
  </pattern>
  <pattern name="location" class="object" description="" weight="1"> 
    <word word="LOCATION" min="1" max="2"/>
  </pattern>
  <pattern name="misc" class="object" description="" weight="1"> 
    <word word="MISC" min="1" max="2"/>
  </pattern>
  <pattern name="org" class="object" description="" weight="1"> 
    <word word="ORG" min="1" max="2"/>
  </pattern>
  <pattern name="gnn" class="object" description="" weight="1"> 
    <word word="GNN" min="1" max="2"/>
  </pattern>

</patterngroup>
